### ISSUE TITLE
Code modularity

### ISSUE THREAD

**Issue by EhsanMashhadi** [reyhanehjaafari/OpenSourceDevelopment#7]
I found that all of your code is in one file which may make it hard to read or change, so I want to ask you to make your model more modular by creating some classes and following the SOLID rules.

**Comment by reyhanehjaafari** [comment]
Thank you for your feedback. I believe you are right.I should have implemented best practices. Can you please change this part?

**Comment by EhsanMashhadi** [comment]
@reyhanehjaafari Sure, I submitted a PR regarding this.

**Comment by abarcomb-work** [comment]
The pull request has been merged, is this issue ready to be closed?

**Comment by reyhanehjaafari** [comment]
@EhsanMashhadi Thank you for the collaboration.
